### PR TITLE
fix indent of multiline string

### PR DESCRIPTION
**Pull request by ppwwyyxx**
close #127 and #129

### CODE REVIEW

**Comment by agronholm** [comment]
I'll need a least one test that fails without this fix.

**Comment by ppwwyyxx** [comment]
Tets was added

**Comment by agronholm** [comment]
Thank you!

**Comment by kylepjohnson** [comment]
Thank you @ppwwyyxx !

Do you know when you will make the next release to PyPI?

**Comment by agronholm** [comment]
Sorry for taking so long but it's out now.

**Comment by shoyer** [comment]
I'm not quite sure why, but it looks like this change broke JAX's doc build: https://github.com/google/jax/pull/6449

**Comment by shoyer** [comment]
For reference, here is the error message that turns up in our logs:
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.8/site-packages/sphinx/events.py", line 111, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.8/site-packages/sphinx_autodoc_typehints.py", line 417, in process_docstring
    type_hints = get_all_type_hints(obj, name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.8/site-packages/sphinx_autodoc_typehints.py", line 271, in get_all_type_hints
    rv = backfill_type_hints(obj, name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.8/site-packages/sphinx_autodoc_typehints.py", line 312, in backfill_type_hints
    obj_ast = ast.parse(textwrap.dedent(
  File "/home/docs/.pyenv/versions/3.8.6/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 12
    max_rows_cols = max(a.shape[-2:])
                                    ^
IndentationError: expected an indented block
```

And the apparent source line:
https://github.com/google/jax/blob/32564442cbab5bec712cadc316a1c01396faf89c/jax/_src/numpy/linalg.py#L304

**Comment by ppwwyyxx** [comment]
Because the decorator contains:
```
    default `rcond` is `1e-15`. Here the default is
```
that starts with "def", the code wrongly assumes this is the function definition line.

Not sure what is a more robust way to find the function definition line of a function source code.

**Comment by shoyer** [comment]
I would look into Python AST, or maybe whatever approaches are used by syntax highlighters. But certainly a line starting with "def" is not a reliable indication :)

**Comment by ppwwyyxx** [comment]
The point of this PR is because we can't use python ast: ast fails to parse a string like
```
    def my_method(self):
        a = '''long
string with bad indentation'''
        return a
```
because the string has to be dedented first. To dedent the string reliably we need to know what's the correct indentation of the function def line.

**Comment by shoyer** [comment]
So I'm not sure how, but both Google Colab and VSCode seem correctly infer the syntax highlighting here:
image

**Comment by shoyer** [comment]
I wonder if the simpler approach of just taking the indentation from the first line in the source code would work. If I understand it correctly, that is always either the function definition itself or a decorator, which must also be intended the same amount as the function definition.

**Comment by agronholm** [comment]
Should I yank the release from PyPI?

**Pull request merged**
