### PR TITLE
Add simplify_optional_unions config option

### LINKED ISSUE #115: Optional[Union[...]] doesn't preserve Optional hint
I noticed that `Optional` `Unions` like `Optional[Union[...]]` become simply `Union[..., None]`. While this is technically still correct I'd prefer for it to preserve the `Optional` type hint.

### PR DESCRIPTION
**Pull request by tillhainbach**
should close #115

Adds a config-option whether Optional[Union[int, str]] should be simplified to Union[int, str, None] or not. Defaults to `True`.

### CODE REVIEW

**Comment by agronholm** [comment]
Why have you reformatted sections of the code that are irrelevant to this patch?

**Comment by tillhainbach** [comment]
Sorry, my bad. Flake8 kept complaining so I quickly ran yapf over the file without checking out into another branch. I reverted the formatting part..

**Comment by agronholm** [comment]
There are still style issues. Once they are resolved to my satisfaction and you have documented this option, I am willing to merge this PR.

**Comment by agronholm** [comment]
It should be noted that when `simplify_optional_unions` is set to `False`, it will also turn any `Union` containing `None` into `Optional[x, y]`, even if Optional was not originally used, right?

**Comment by agronholm** [comment]
Oh, I almost forgot: would you mind adding a test for this in the existing test suite? Maybe just something minimal to make sure it generates the expected result with the flag turned on and off.

**Comment by tillhainbach** [comment]
I'll add a tests for the option later. However, I cannot get all test to pass. `test_sphinx_output` will always fail. This also happens for me with the HEAD version of this repo's master.

```
py38 run-test: commands[0] | python -m pytest
===================================== test session starts =====================================
platform darwin -- Python 3.8.2, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
cachedir: .tox/py38/.pytest_cache
rootdir: /Users/tillhainbach/sphinx-autodoc-typehints, inifile: setup.cfg, testpaths: tests
collected 86 items                                                                            

tests/test_sphinx_autodoc_typehints.py ................................................ [ 55%]
....................................FF                                                  [100%]

========================================== FAILURES ===========================================
__________________________________ test_sphinx_output[True] ___________________________________
tests/test_sphinx_autodoc_typehints.py:505: in test_sphinx_output
    assert text_contents == expected_contents
E   AssertionError: assert 'Dummy Module...-- function\n' == 'Dummy Module...-- function\n'
E     Skipping 2275 identical leading characters in diff, use -v to show
E     - fault(x='\x08')
E     + fault(x='\\x08')
E     ?           +
E       
E          Function docstring.
E       ...
E     
E     ...Full output truncated (121 lines hidden), use '-vv' to show
---------------------------------- Captured stdout teardown -----------------------------------
# testroot: root
# builder: text
# srcdir: /private/var/folders/ct/ygv9rcqn44q1r6qzscvvvlz80000gr/T/pytest-of-tillhainbach/pytest-20/dummy
# outdir: /private/var/folders/ct/ygv9rcqn44q1r6qzscvvvlz80000gr/T/pytest-of-tillhainbach/pytest-20/dummy/_build/text
# status: 
Running Sphinx v3.0.3
building [mo]: targets for 0 po files that are out of date
building [text]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                 
build succeeded, 4 warnings.

The text files are in ../../../private/var/folders/ct/ygv9rcqn44q1r6qzscvvvlz80000gr/T/pytest-of-tillhainbach/pytest-20/dummy/_build/text.

# warning: 
WARNING: Cannot treat a function defined as a local function: "dummy_module.Class.locally_defined_callable_field"  (use @functools.wraps)
WARNING: Cannot resolve forward reference in type annotations of "dummy_module.function_with_unresolvable_annotation": name 'a' is not defined
WARNING: Cannot treat a function defined as a local function: "dummy_module.DataClass"  (use @functools.wraps)
WARNING: Cannot treat a function defined as a local function: "dummy_module.DataClass.__init__"  (use @functools.wraps)

__________________________________ test_sphinx_output[False] __________________________________
tests/test_sphinx_autodoc_typehints.py:505: in test_sphinx_output
    assert text_contents == expected_contents
E   AssertionError: assert 'Dummy Module...-- function\n' == 'Dummy Module...-- function\n'
E     Skipping 2275 identical leading characters in diff, use -v to show
E     - fault(x='\x08')
E     + fault(x='\\x08')
E     ?           +
E       
E          Function docstring.
E       ...
E     
E     ...Full output truncated (118 lines hidden), use '-vv' to show
---------------------------------- Captured stdout teardown -----------------------------------
# testroot: root
# builder: text
# srcdir: /private/var/folders/ct/ygv9rcqn44q1r6qzscvvvlz80000gr/T/pytest-of-tillhainbach/pytest-20/dummy
# outdir: /private/var/folders/ct/ygv9rcqn44q1r6qzscvvvlz80000gr/T/pytest-of-tillhainbach/pytest-20/dummy/_build/text
# status: 
Running Sphinx v3.0.3
building [mo]: targets for 0 po files that are out of date
building [text]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                 
build succeeded, 4 warnings.

The text files are in ../../../private/var/folders/ct/ygv9rcqn44q1r6qzscvvvlz80000gr/T/pytest-of-tillhainbach/pytest-20/dummy/_build/text.

# warning: 
WARNING: Cannot treat a function defined as a local function: "dummy_module.Class.locally_defined_callable_field"  (use @functools.wraps)
WARNING: Cannot resolve forward reference in type annotations of "dummy_module.function_with_unresolvable_annotation": name 'a' is not defined
WARNING: Cannot treat a function defined as a local function: "dummy_module.DataClass"  (use @functools.wraps)
WARNING: Cannot treat a function defined as a local function: "dummy_module.DataClass.__init__"  (use @functools.wraps)

====================================== warnings summary =======================================
tests/test_sphinx_autodoc_typehints.py:206
  /Users/tillhainbach/sphinx-autodoc-typehints/tests/test_sphinx_autodoc_typehints.py:206: PytestUnknownMarkWarning: Unknown pytest.mark.sphinx - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    @pytest.mark.sphinx('text', testroot='dummy')

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=========================== 2 failed, 84 passed, 1 warning in 2.23s ===========================
ERROR: InvocationError for command /Users/tillhainbach/sphinx-autodoc-typehints/.tox/py38/bin/python -m pytest (exited with code 1)
flake8 create: /Users/tillhainbach/sphinx-autodoc-typehints/.tox/flake8
flake8 installdeps: flake8
flake8 installed: flake8==3.8.1,mccabe==0.6.1,pycodestyle==2.6.0,pyflakes==2.2.0
flake8 run-test-pre: PYTHONHASHSEED='3565312246'
flake8 run-test: commands[0] | flake8 sphinx_autodoc_typehints.py tests
sphinx_autodoc_typehints.py:130:23: F522 '...'.format(...) has unused named argument(s): prefix
ERROR: InvocationError for command /Users/tillhainbach/sphinx-autodoc-typehints/.tox/flake8/bin/flake8 sphinx_autodoc_typehints.py tests (exited with code 1)
___________________________________________ summary ___________________________________________
SKIPPED:  py35: InterpreterNotFound: python3.5
SKIPPED:  py36: InterpreterNotFound: python3.6
SKIPPED:  py37: InterpreterNotFound: python3.7
ERROR:   py38: commands failed
ERROR:   flake8: commands failed
```

Same failures prevent test passing for PR #138

**Comment by agronholm** [comment]
These are existing problems that I need to solve. You don't need to worry about them.

**Comment by agronholm** [comment]
Looking good – I'll try to get the upstream test failures resolved Real Soon (tm).

**Comment by tillhainbach** [comment]
I update my PR from upstream/master as suggested by @mitar https://github.com/agronholm/sphinx-autodoc-typehints/pull/143#issuecomment-647780223

Tests should pass now.

**Comment by h1nk** [comment]
@agronholm hey think we could get this merged into master now with the tests resolved?

**Comment by agronholm** [comment]
Done! Thank you for your contribution.

**Pull request merged**
