### PR TITLE
Identify typing.NewType wrappers and construct annotation references

### LINKED ISSUE #41: Types created with NewType are rendered poorly.
If I have code like:
```
    Foo = typing.NewType('Foo', str)
    def bar(x: Foo):
        pass
```
then its parameter gets documented as:
```
    x (<function NewType.<locals>.new_type at 0x7f644b4c6488>)
```
I was expecting something like one of the following:
```
    x (Foo)
    x (Foo alias for str)
    x (str)
```

### PR DESCRIPTION
**Pull request by gwax**
Resolves #41 producing output of the form `NewType(NewName, OldType)` with appropriate references.

### CODE REVIEW

**Comment by rmorshea** [comment]
@agronholm thoughts on this?

**Comment by agronholm** [comment]
I'll try to take a look at this this weekend.

**Comment by agronholm** [comment]
Thanks!

**Comment by agronholm** [comment]
@gwax I've been rechecking the code and I cannot figure out why you chose to format the name of the NewType as `:py:data:~TypeName`. Shouldn't it contain the module name as well, like `:py:data:~module.name.TypeName`? I'm also wondering if the formatting scheme is even in the right direction. Maybe just `:py:data:~module.name.TypeName` should be used, without involving `typing.NewType`?

**Comment by agronholm** [comment]
Ok, the module name containing the new type is not recorded anywhere so this is the best we can do. Sorry for the noise :)

**Pull request merged**
